app/models/user.rb, db/migrate/20200130192231_create_category_users.rb, db/migrate/20200130200321_add_attributes_to_user.rb, db/schema.rb
Added migration to give User the extra attributes and added validations for them
Pls review and pull fam <3
=> User validation

app/models/booking.rb
Added validations to Booking model
Pls review and pull, fam <3
=> Validation booking

app/models/activity.rb, app/models/category.rb, app/models/category_user.rb, app/models/review.rb, app/models/user.rb
Added validations and relations for all our models, except Activity's weather_params - will be done when we find an API we willl use for them :)
=> Validations and relations

Gemfile, Gemfile.lock, app/models/user.rb, config/initializers/geocoder.rb, db/migrate/20200201095345_add_coordinates_to_users.rb, db/schema.rb
Hello homies, please inspect this and do a db:migrate to get the latest db updates mein batmans
=> Geocoding fun

app/controllers/users_controller.rb, app/views/users/create.html.erb, app/views/users/dashboard.html.erb, app/views/users/delete.html.erb, app/views/users/edit.html.erb, app/views/users/index.html.erb, app/views/users/new.html.erb, app/views/users/show.html.erb, app/views/users/update.html.erb, config/routes.rb
Ditched the useless User-views and routes and redirected everything to work with Devise default. Added 'dashboard' as route, which uses Users-controller as its linked method - this will automatically send the user to the sign-up/sign-in page if s/he isn't logged in. This means Dashboard is the new root:home.
Pls review n pull comradinhos
=> More routes

app/controllers/categories_controller.rb, app/controllers/users_controller.rb
Implemented basic logic for Categories, minus delete for now
=> Category controller

app/controllers/activities_controller.rb
Implemented basic logic for Activies, minus delete for now
=> Activities controller

db/migrate/20200201135515_remove_field_time_from_table_user.rb, db/schema.rb
Yoooo
Since I removed some stuff from the db...
well you guess d it 
run a DB:MIGRATE!!!!!!
you dumbass
love love
=> I removed the time and day preference

app/controllers/activities_controller.rb, app/controllers/reviews_controller.rb, app/models/booking.rb, app/views/reviews/create.html.erb, app/views/reviews/delete.html.erb, app/views/reviews/edit.html.erb, app/views/reviews/index.html.erb, app/views/reviews/new.html.erb, app/views/reviews/show.html.erb, app/views/reviews/update.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
Removed all the unnecessary fluff from Reviews (views + all methods except new and create) and implemented new and create-methods properly.
Nested Reviews-routes under Bookings-routes and set up the logic to be used in our simple_forms when making reviews of bookings.
3< maf llup dna weiver slP
=> Reviews controller and polishes

Gemfile, Gemfile.lock, db/migrate/20200201150705_add_time_preferences_to_users.rb, db/schema.rb
So you will need another db:migrate homies
=> added the time preferences attributes under the DateTime datatype

app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb
no migration to run this time :)
=> the description is in my branch title (yes I am lazy)

app/views/users/dashboard.html.erb
So our beautiful index is visible :)
=> Fixed the navigation to the Categories-index

db/seeds.rb
Gives us some stuff to play around with :)
Feel free to add or edit categories or activities as we go along
=> Added 5 cats in total w 3 activities each

app/controllers/activities_controller.rb, app/controllers/users_controller.rb, app/models/activity.rb, app/views/activities/create.html.erb, app/views/activities/edit.html.erb, app/views/activities/index.html.erb, app/views/activities/show.html.erb, app/views/activities/update.html.erb, app/views/shared/_activities_new_edit.html.erb, app/views/shared/_navbar.html.erb, app/views/users/dashboard.html.erb, db/migrate/20200130194659_create_activities.rb, db/migrate/20200208103134_add_title_to_activity.rb, db/schema.rb, db/seeds.rb
Added Activities index, create and show, and made a series of bugfixes to the displays that require attached photos
=> Activities crude views and creation

app/assets/javascripts/application.js, app/assets/stylesheets/pages/_login-page.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
I know form are "useless" to work on but I still made them a little bit less boring with basic JS. Hope you like it.
=> Login form

app/models/booking.rb, db/schema.rb, db/seeds.rb
This doesn't actually touch the mail->booking linking. Instead it adds Seeds for 10 completed activities for all users.
=> Added seed for completed bookings (10) for users

app/controllers/bookings_controller.rb, app/mailers/user_mailer.rb, app/models/activity.rb, app/models/booking.rb, app/models/user.rb, app/views/bookings/delete.html.erb, app/views/user_mailer/offer_activities.html.erb, app/views/users/dashboard.html.erb, config/routes.rb
Set up the activity-offering-logic in the emails (in development environment)
=> Url for user email

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_contact-card.scss, app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_feed.scss, app/assets/stylesheets/components/_index.scss, app/controllers/users_controller.rb, app/views/users/dashboard.html.erb
Start of the weather API still some work must be done
=> Weatherapi

app/views/users/dashboard.html.erb, db/migrate/20200222103538_remove_address_from_users.rb, db/migrate/20200222110649_add_city_to_users.rb, db/migrate/20200222110734_add_admin_to_users.rb, db/schema.rb
you will need a db migration homies
=> Dbmigrationsss

app/controllers/activities_controller.rb, app/models/activity.rb, app/views/activities/activities_for_approval.html.erb, app/views/activities/custom_activities.html.erb, app/views/activities/index.html.erb, app/views/categories/index.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
Made it possible to deny submitted Activities
Changed the admin view to a new button in the navbar that does the same approval-thingy as the old 'pending activities'-button/view did (this is now the functionality below).
Added a view for the user to see her own submitted activities that are pending approval.
Pls review and pool fam :)
=> Activity denial logic and more

app/controllers/users_controller.rb, app/models/booking.rb, app/views/users/dashboard.html.erb, db/migrate/20200227231312_add_date_completed_to_bookings.rb, db/schema.rb
=> Gamifying dashboard

app/assets/stylesheets/components/_card-count.scss, app/assets/stylesheets/components/_contact-card.scss, app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_weatherWidget.scss, app/controllers/users_controller.rb, app/models/booking.rb, app/models/user.rb, app/views/shared/_navbar.html.erb, app/views/users/dashboard.html.erb, db/seeds.rb
Updated Dashboard - changed the center column to have less space so to show the statistics a bit more. Made the name a bit larger. Changed navbar order and capitalized all major words. Centered the quote in the left column.
Pls review and pool :)
=> Dashboard beautifying

app/assets/stylesheets/components/_card-count.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_contact-card.scss, app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_feed.scss, app/assets/stylesheets/components/_quote.scss, app/controllers/users_controller.rb, app/models/booking.rb, app/views/categories/index.html.erb, app/views/shared/_navbar.html.erb, app/views/users/dashboard.html.erb, public/422.html, public/500.html
=> Updated UI

app/views/user_mailer/offer_activities.html.erb
=> FIXED THE EMAIL BUG ERMAGAD
